### PR TITLE
Match semver versions better, as detailed in #53

### PR DESCRIPTION
**Pull request by sambryant4**
This PR is to resolve the issue: #53 the approach taken is basically an improved regex to match any tags that have a semver version as a prefix, allowing a `v` to be an optional starting character.

Some general tidy up changes have also been included that could be considered opinionated so please say if you want those removed. For example, preventing globbing/ word splitting of variables in some scripts and changing the counterfeiter command so that rerunning `go generate ./...` automatically updates the `fakes` directory instead of creating a brand new `github-release-resourcefakes` directory.

### CODE REVIEW

**Comment by jtarchie** [comment]
Please see [my comment](https://github.com/concourse/github-release-resource/issues/53#issuecomment-327212546) on #53.

**Comment by srbry** [comment]
Added comments to #53 explaining the latest changes, hopefully this is now acceptable.

**Comment by jtarchie** [comment]
@srby, thanks for the updates. You added a lot of features, which are not clear if they needed to be added.

My original feedback was about the `tag_filter` option. For clarification, since certain *semver* tags need to be extracted, it would be nice if the `tag_filter` worked like the s3 resource `regexp`. It has a capture group for the version to look for. 

This way `tag_filter` can just default to the current `v(\d+)` regex, and others can configure that value.

**Comment by willejs** [comment]
@sambryant4 any news on this?

**Comment by srbry** [comment]
@willejs @jtarchie sorry for the late response. I came to the conclusion that allowing a custom tag filter at all would allow matching of versions that were not `semverish` and therefore wouldn't make sense to the ordering. I think adding the ability to sort by date is the only thing that makes sense if we want to allow `tag_filter`.

I guess a compromise could be forcing all versions to be `semver` and allowing the `tag_filter` option to be run after a generic "semver filtering" type activity?

**Comment by vito** [comment]
@srbry Gotcha. Do you have an example of a case where `tag_filter` would not be sufficient? In the original use case for example, it should work fine, since the tags do have a version in them, just with a different prefix. In fact, you may not want `date_order` since they often release patches of older versions - you wouldn't want that to become the latest overall.

I think this is a lot simpler as just `tag_filter`. If there's another case that proves the need for `date_order` we can tackle it then, but I don't want to preemptively make the interface more complicated. The original issue would then be fixed by default by having `tag_filter` default to `^v([\d\.]+)$`.

**Comment by pivotal-issuemaster** [comment]
@sambryant4 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/github-release-resource&pullRequestId=54)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/github-release-resource&pullRequestId=54) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by vito** [comment]
I'm gonna close this since it's getting stale, sorry.

**Pull request closed without merging**
