### PR TITLE
Update dependencies and try to fix download assets

### PR DESCRIPTION
**Pull request by kirillbilchenko**
Go release resource is not able to download release assets, for some reason redirection url returing wrong url, so I want to update dependencies for latest go-github version

### CODE REVIEW

**Comment by xtremerui** [comment]
Is there a known bug or issue that we could reference from?  With current version in our CI it seems working fine. Wondering what exactly cause it failed in your case. Thx.

**Comment by kirillbilchenko** [comment]
@xtremerui for  me it's failing to  download the release for this https://github.com/hellofresh/ggr I need to download the latest release, for some  reason the redirection link in concourse returning asset  for `&response-content-disposition=attachment%3B%20filename%3Dggr_darwin_amd64&response-content-type=application%2Foctet-stream" responded with bad status code: 404` but we don't even have darwin there, only linux, so  I was  thinking maybe it's something wrong with client

**Comment by kirillbilchenko** [comment]
@xtremerui also  I  checked in  command, maybe you have any  idea why it can  pick up the wrong asset, seems like the release id is correct but the file name returned by url for some reason is wrong, I manually checked the github api, and it's returning correct assets

**Comment by xtremerui** [comment]
so have you tried any other github release with your current Concourse installation? You could also try building the image and push to your dockerhub to verify the dependency bump will actually fix your problem.

**Comment by kirillbilchenko** [comment]
> so have you tried any other github release with your current Concourse installation? You could also try building the image and push to your dockerhub to verify the dependency bump will actually fix your problem.

@xtremerui sure will do and will back with result

**Comment by kirillbilchenko** [comment]
@xtremerui I  build and new image and found out the problem, it was with the previous release, for some reason it had an asset for darwin which was broken, but as for me, I don't see a problem updating the dependencies.

**Comment by xtremerui** [comment]
Good to know that it was the issue from github not the resource type.

I will mark this PR as a dependency update instead of bug fix. Thank you for all the work!

**Pull request merged**
