### PR TITLE
Rate limit issues found update README

### PR DESCRIPTION
**Pull request by sandyg1**
Found token was rate limited to 60 when a scope was chosen for a public repo
@vito

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sandyg1 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/github-release-resource&pullRequestId=46)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/github-release-resource&pullRequestId=46) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sandyg1 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/github-release-resource&pullRequestId=46)!

**Comment by chendrix** [comment]
I'm unfortunately going to reject this PR, @sandgy1

You need those scopes if you are doing a `put` with this resource, you cannot use a no-scoped token unless you are just performing `get`. And I don't want to [duplicate effort/documentation](https://github.com/concourse/concourse/wiki/Anti-Patterns#duplicate-effort) that might become out of date if Github later changes their rate limiting.

**Comment by chendrix** [comment]
Thank you for using Concourse and for taking the time out of your busy schedule to write this PR though, @sandyg1 !

**Pull request closed without merging**
