### PR TITLE
add example of getting a specific release version

### PR DESCRIPTION
**Pull request by mdb**
This tripped me up; hoping this helps others!

Thanks for your great work.

### CODE REVIEW

**Comment by vito** [comment]
Thanks! Though, this is missing some details that are present in [the docs](https://concourse.ci/get-step.html#get-version) - namely that you'll probably need to run `check-resource` first. Maybe this should just link to the docs instead?

Or...maybe there's something we can do to make the docs more discoverable? I don't want every resource author to have to document this.

**Comment by mdb** [comment]
I see. I'd like to help make such usage information easy to access and understand for sometimes-naive users like me. Please let me know if I can help towards this goal.

**Comment by vito** [comment]
I'll just go ahead and merge this since it's at least useful on its own. In the future I think we may want to have resources just document their version format as part of the README.

Thanks!

**Comment by mdb** [comment]
Thanks!

**Pull request merged**
